### ISSUE TITLE
palette colours org-b2b-* to be deprecated?

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-colors#115]
Unless they are being used by anyone else KAT was the only product that used org-b2b-* colours

**Comment by Thurst-ft** [comment]
Not sure if this will affect the decision to depreciate org-b2b-* but it seems that http://enterprise.ft.com/en-gb/ is using the orange from o-color palette.

**Comment by onishiweb** [comment]
Have looked through the GH codebases and it appears in 2 places, one in Origami (o-labels) and one in AMP. Looks like it should be safe to deprecate and move to something within the new palette.
