### ISSUE TITLE
new advertising colour

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/o-colors#120]
hi Origami,

I'm not sure if this is the correct way to raise this. I've added a o-label to the updated design of the paid post teaser that runs across FT.com (see attached)

How is the best way to add this colour into the Origami colour component. Also it needs to be called Advertising, or Paid Post or Promoted Content or something. Any thoughts on this are welcome.

[paid post unit.pdf](https://github.com/Financial-Times/o-colors/files/766572/paid.post.unit.pdf)
@andygnewman @alicebartlett 

The colour is #18806F

**Comment by alicebartlett** [comment]
@onishiweb and @olipowell are in the middle of a big colors refactor, can you two decide on this pleaseeeee?

**Comment by onishiweb** [comment]
Talked with @olipowell and decided to use `teal` instead
