### ISSUE TITLE
Add FT Brand Pink

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-colors#138]
Although we don't want to use the brand pink in digital things, @rowanbeentje has come up with valid use-case for it which is preventing a flash of the wrong colour content when the logo loads in. 
Once I have the hex value for the color I propose we add it under a new category of colors called "brand colors" and we call it brand-ft-pink.

**Comment by alicebartlett** [comment]
According to the FT brand guidelines (https://drive.google.com/file/d/1a78OYPFjHrx6UcFdLNV8Z2S_ZyoWmzmo/view) the hex for the RGB for FT brand pink is #fcd0b1

**Comment by gvonkoss** [comment]
@rowanbeentje is this still relevant?

**Comment by rowanbeentje** [comment]
@gvonkoss  I think so!  "Brand" FT pink (like that used in the logo background) isn't in the current pallette, so we've ended up hardcoding it - I think the reason it wasn't included originally is because we didn't want to have it used for UI elements etc, so not sure how that can be discouraged...

**Comment by gvonkoss** [comment]
@notlee we can probably add this to the list of things to do when we brand components (I can't remember what our final decision with branding regarding  `o-colors` was)

**Comment by rowanmanning** [comment]
@notlee to check if there are any other use-cases for this?
