### ISSUE TITLE
implement o-brand

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-colors#144]
A comment in #143 raised a use case for `o-brand`, but @notlee and I have agreed to postpone its implementation so that we have the opportunity to brand more components and  pick up on any additions/changes we'd like to make to `o-brand` before we include it here and cause any breaking changes.

**Comment by notlee** [comment]
Also hide the redundant white tints in the "internal" brand demo. Potential implementation: give origami.json demos an array for which brands they apply to, show in the registry ui based on the selected brand.

https://github.com/Financial-Times/o-colors/pull/145

**Comment by notlee** [comment]
We've branded o-colors now and are making improvements in v5, see
https://github.com/Financial-Times/o-colors/pull/207
