### ISSUE TITLE
Removing tinting (aka breaking changes)

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-colors#148]
We've  found that the concepts of 'tinting' and 'mixing' are inaccurately represented in`o-colors`, especially now that we are beginning to introduce `o-brand` to our components. Seeing as the fundamental concept behind branding is that we provide the ability to switch stylistic context, we need a palette that supports those switches.

Currently, `o-colors` doesn't support colours/tints/shades/mixes (that are not experimental) for the `internal` brand. And as we have branded components, we've come to find that the tinting mechanism is heavily based on FT.com designs (e.g. `black-20` isn't a shade of grey, it is a mix of `black` and `paper`). 

Furthermore, the implication that we supply tints is incorrect. The existing tinted palette colours are actually shaded or lightened basted on lightness and saturation _not_ tinted with another colour.
In reality, what is 'tinted' are the colours that are processed through `oColorsMix` 

Our proposal, in the long term, is to alter the functionality of the mixins that construct the palette as we know it. We want to provide branding for `o-colors` it so that we might generate a clearer functionality and greater flexibility in terms of the colours that are available.

Tagging @notlee as the other half of this conversation.

**Comment by notlee** [comment]
There wasn't much appetite from the design team or others I chatted to to rename our palette colours to make the distinction between tints and... tones(?) more explicit. We decided to improve our documentation but not make other changes for the time being. There are some more details here https://github.com/Financial-Times/o-colors/issues/198

**Comment by notlee** [comment]
Scratch that. Tints are tones and mixes are mixes. Hi Gabi 👋
