### ISSUE TITLE
Should we remove or reduce the contrast checking?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-colors#192]
Based on a discussion with @oliverturner in the open meeting. The contrast checker built into o-colors is possibly not needed, as most of our users (us included) run automated accessibility tests. We could either remove or allow people to disable the warnings.

**Comment by notlee** [comment]
The immediate issue is addressed in https://github.com/Financial-Times/o-colors/pull/193 and https://github.com/Financial-Times/o-colors/pull/196, in that warnings are no longer output with silent mode enabled (as the user can't do anything about them). I also created an issue to consider removing the CSS classes which are causing the contrast warnings in the next breaking release https://github.com/Financial-Times/o-colors/issues/194. They may no longer be useful as many of our build service uses can rely on CSS custom properties.

I'd suggest keeping this issue open for now as if we decide to remove contrast checking entirely from o-colors we might also want to ensure our users are making the post of post-build tools like Pa11y first. Maybe run some workshops if not :D

**Comment by chee** [comment]
i think the contrast testing belongs outside of o-colors

**Comment by notlee** [comment]
> i think the contrast testing belongs outside of o-colors

I largely agree. The [proposal for v5 ](https://github.com/Financial-Times/o-colors/issues/198)reduces contrast checking in o-colors, except for `oColorsGetTextColor` where a foreground colour is generated. My thinking is in that case immediate feedback is useful. Provided it may be addressed or dismissed. Thoughts?

**Comment by chee** [comment]
@notlee doing some but not much contrast checking feels like it light lead people into a false sense of security?

and if we’re expecting them to use a further tool for the rest of the contrast checking then they get it in two places.

i think we should leave color accessibility to a tool like Pa11y.

does Typography warn if a font size is too small?

**Comment by notlee** [comment]
@chee it does not, I suppose you're right that we don't want to create a false sense of security. I'll update the proposal to remove all contrast checking.

**Comment by rowanmanning** [comment]
This can be closed as it's in the proposal #198 and will be done as part of the next breaking change (#199)
