### ISSUE TITLE
Add mandrain back to the internal tool palette?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-colors#245]
We're using the hex directly for `o-meter`. Should it be officially available for 
internal brand products again? My feelings are it should if:
- there are other uses of the hex directly in internal brand products, or;
- the design team foresee using it in internal brands products in the future

https://github.com/Financial-Times/o-meter/pull/7#discussion_r384390034

**Comment by rowanmanning** [comment]
@kiyaGu has another use-case in biz-ops, an amber label (and also there's an orange used in SOS for amber ratings). I'm going to open a PR adding mandarin to the internal brand I think, otherwise Kiya will have to copy/paste the hex in another place.
