### ISSUE TITLE
Inconsistent status of wasabi

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/o-colors#309]
The v4 to v5 migration is explicit in its mention of the deprecation of `wasabi` https://github.com/Financial-Times/o-colors/blob/master/MIGRATION.md#sass:
```
Deprecated internal and whitelabel brand palette colours were removed. Please contact Origami if your product has a usecase for one of the removed colours:

Internal brand: candy, wasabi, org-b2c, org-b2c-dark, org-b2c-light, paper, wheat, sky, velvet, mandarin, claret.
Whitelabel brand: all colours except black and white have been removed.
```

However, the tertiary color palette still shows wasabi: https://registry.origami.ft.com/components/o-colors@6.0.3#demo-tertiary-palette

**Comment by notlee** [comment]
That view shows the master brand colour palette. To see the internal brand palette toggle the brand in the right hand sidebar :) ![Screenshot 2021-07-27 at 11 52 02](https://user-images.githubusercontent.com/10405691/127142275-6d070e5a-3ff0-4f30-a127-b7076e9cd819.png)
![Screenshot 2021-07-27 at 11 51 58](https://user-images.githubusercontent.com/10405691/127142281-7274a940-200f-4f4c-b752-cb9029816cda.png)

**Comment by notlee** [comment]
There is a related issue though that @kiyaGu found :D https://github.com/Financial-Times/o-colors/pull/310
