### ISSUE TITLE
Weekend header color

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-colors#65]
Use-cases don't include section-red for the "WEEKEND" in the header:

![screen shot 2014-07-28 at 20 35 10](https://cloud.githubusercontent.com/assets/72159/3725953/60c552c0-168e-11e4-9fb3-af9bb49d65d7.png)

We currently (ab)use `oColorsGetColorFor(section-money-text)` for this.

**Comment by kaelig** [comment]
Is this still an issue?

**Comment by pornel** [comment]
Yes.

**Comment by pornel** [comment]
I don't see a solution for this.

**Comment by onishiweb** [comment]
There's `o-section-red` now in the palette, so I'm going to close this one.
