### ISSUE TITLE
RGBA

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-colors#71]
New proposed approach for RGBA, building on top of the new refactored module:

* Palette is modified to include RGBA with solid fallback where appropriate:

```scss
$o-colors-palette: (
        pink:                 rgba(255, 200, 200, 0.4) #fff1e0,
        black:                rgba(0,0,0,0.9) #000000,
        blue:                 #0000ff
```

* `oColorsFor` now returns two rules for each property if a transparent version is defined
* `oColorsGetColorFor`, and `oColorsGetPaletteColor` take one additional argument for whether to return the rgba or the solid.  If not specified, returns the solid.

**Comment by onishiweb** [comment]
Is this still an issue?

**Comment by kavanagh** [comment]
Don't think so. If it turns out to be important someone can reopen.
