### ISSUE TITLE
Namespace palette colours to make linting easier

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-colors#72]
Following #69, I'm breaking this out.  The problem is that this:

```
@include oColorsSetUseCase(blah, border, white);
```

upsets sass-lint because it doesn't like the use of the word 'white'.  Even though we're using it as a string parameter, not a CSS colour.

Can we placate the linter, or should we namespace the colours. 

We're currently working around this by disabling that lint check.

**Comment by kaelig** [comment]
Not an issue anymore since we're quoting color names.
