### ISSUE TITLE
Namespaced colour schemes

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-colors#86]
Possible way to approach supporting next but avoiding a mass refactor of next when o-colors is updated to use next's colour scheme

```sass
// in o-colors
$o-colors-use-palette: origami !default;

$o-colors-palettes: (
	origami: ( 
          //existing palette goes in here
        )
)

// then getColorFor would then do something like
$color: map-get(map-get($o-colors-palettes, $o-colors-use-palette), $use-case)

// In next code
map-set($o-colors-palettes, next, (
    //next palette in here 
))
$o-colors-use-palette: next;
```

Then can just use o-colors in the standard way and next colours will get applied to any origami components we use. When the day comes to update origami to use next colours we just replace the origami palette with the next one.

@kaelig

**Comment by triblondon** [comment]
Would you use all the same colour names?

The problem if you don't is that the palettes are not interchangeable.

**Comment by triblondon** [comment]
My preference is simply to add new colours.  If necessary, `next-pink` etc.  Eventually `pink` will be deprecated, and then even more eventually, `pink` can be an alias for `next-pink`.

**Comment by wheresrhys** [comment]
I realised there was a flaw in what I suggested. What I should have referenced in my suggestion was `$o-colors-usecases`. The problem is not just about defining new colours, it's about pointing use cases at next's choice of colour so e.g. a link in o-comments should use next's choice of link colour when on next.

**Comment by kaelig** [comment]
Isn't it for o-comments to define use cases to be customisable?

**Comment by wheresrhys** [comment]
Just been reading the o-colors code. `oColorsSetUseCase()` will override existing use cases, is that right?

**Comment by kaelig** [comment]
I never used it in a product but I think you're looking in the right direction.

**Comment by kaelig** [comment]
o-colors v3 allows to use new colors, can I close this question?

**Comment by wheresrhys** [comment]
yep by all means
