### ISSUE TITLE
Expose palette and use-case names in a format readable by PHP and/or JS

### ISSUE THREAD

**Issue by pornel** [Financial-Times/o-colors#89]
The image service accepts [background and tint colours](http://image.webservices.ft.com/v1/#bgcolor). It'd be great if it could accept Origami colour names.

I'd rather avoid writing regexes to fish colours out of SCSS files.

Perhaps related to #47

**Comment by kaelig** [comment]
With LibSass and node-sass it will be easier to pass JSON to Sass as a map. So this is a way we could look into.

In the mean time, a custom made JSON -> Sass generator launched through a task could also work.

The only issue is that modules can extend the palette. This is much harder to port to JSON. Any suggestions?

**Comment by pornel** [comment]
Can you give an example how the palette is extended? Maybe it doesn't have to be supported, or maybe it can be a per-module json.

**Comment by kaelig** [comment]
Here is an example: https://github.com/Financial-Times/o-header/blob/master/src/scss/_color-use-cases.scss

```scss
@include oColorsSetUseCase(o-header, background, 'grey-tint5');
@include oColorsSetUseCase(o-header-item, background, 'grey-tint5');
@include oColorsSetUseCase(o-header-item, border, 'grey-tint4');
@include oColorsSetUseCase(o-header-item, text, 'white');
@include oColorsSetUseCase(o-header-item-active, background, 'pink-tint2');
@include oColorsSetUseCase(o-header-item-active, background, 'blue');
```

**Comment by pornel** [comment]
How far off are you from using JSON in Sass? Will it "just work" with existing deployments? (i.e. without an extra preprocessing step?)

I think I'd be OK if extensions required an extra lookup step (in this case if there was e.g. `o-header/palette.json` that contained `{"o-header-item":{"background":"grey-tint5"}}` and required looking up `grey-tint5` in `o-colors/palette.json` or such).

**Comment by kaelig** [comment]
No idea, really. Haven't had a proper look at things like Eyeglass yet.

The only issue is that we'd have to discuss is that it would be an extra dependency that isn't compatible with the Sass spec, but is an extension of node-sass (itself based on LibSass).

**Comment by pornel** [comment]
Oh, I thought that by node-sass you've meant the Ruby Sass.

So if officially it's not possible to load a JSON, then maybe generate it from Sass (with an ugly regex after all)

**Comment by kaelig** [comment]
That's feasible. Let's see…

@hugogiraudel built SassyJSON a while ago, but maybe there are better tools to read JSON in Sass nowadays?

**Comment by HugoGiraudel** [comment]
> @hugogiraudel built SassyJSON a while ago

Don't. It's broken since 3.4.

**Comment by HugoGiraudel** [comment]
What do you use: Ruby Sass or LibSass?

**Comment by kaelig** [comment]
We're in the process of switching to LibSass.

**Comment by HugoGiraudel** [comment]
You want to export Sass or import JSON?

**Comment by kaelig** [comment]
Either is fine, potentially dynamic so that we don't have a build step but that's not a requirement.

We just want colors and use-cases to be available to all programming languages, so JSON seems like a good format for that. It doesn't really matter how that is done (data direction, number of steps…).

**Comment by HugoGiraudel** [comment]
There you have it: http://sassmeister.com/gist/651b47182c7e985306b0.

**Comment by kaelig** [comment]
Sweeeeet.

@pornel looks like something that's easy to read for JS or PHP (without a complicated regex).
@AlbertoElias any idea how we could output this easily? Could it be something OBT does compile?

**Comment by HugoGiraudel** [comment]
If you generate this:

```scss
@error o-json-encode($o-colors-palette);
```

You get this:

```css
'{"transparent": "transparent", "transparent": "transparent", "inherit": "inherit", "pink": "#fff1e0", "pink": "#fff1e0", "black": "#000000", "black": "#000000", "white": "#ffffff", "white": "#ffffff", "blue": "#2e6e9e", "blue": "#2e6e9e", "dark-blue": "#275e86", "claret": "#9e2f50", "orange": "#d66d06", "orange": "#d66d06", "grey-tint1": "#b0b0b0", "grey-tint2": "#999999", "grey-tint3": "#777777", "grey-tint4": "#505050", "grey-tint5": "#333333", "pink-tint1": "#f6e9d8", "pink-tint2": "#e9decf", "pink-tint3": "#cec6b9", "pink-tint4": "#a7a59b", "pink-tint5": "#74736c", "red": "#cc0000", "red": "#cc0000", "green": "#458b00", "green": "#458b00", "orange-tint1": "#eda45e", "brown-tint1": "#94826b", "yellow-tint1": "#eed485", "green-tint1": "#a6a471", "bluegreen-tint1": "#819e9a", "silver-tint1": "#c1b8b4", "purple-tint1": "#936971", "purple-tint2": "#737e7e", "red-tint1": "#b1493f", "red-tint2": "#c36256", "red-tint3": "#d17c70", "red-tint4": "#df9c92", "red-tint5": "#ebbcb3", "blue-tint1": "#598caf", "blue-tint2": "#75a5c2", "blue-tint3": "#8ab5cd", "blue-tint4": "#a9cadc", "blue-tint5": "#bcd7e5", "section-purple": "#92288f", "section-light-purple": "#ebcaec", "section-blue": "#0e6dcc", "section-light-blue": "#c5d4e8", "section-green": "#09a25c", "section-light-green": "#a1dbb2", "section-red": "#cc0033"}'
```

Then in PHP:

```php
$contents = file_get_contents(url + 'json-colors.scss');
try {
  $colors = json_decode($contents);
} catch (Exception $e) {
  echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

Or in JavaScript (pardon jQuery):

```js
$.ajax(url + 'json-colors.scss)
  .done(function (data) {
    try {
      var colors = JSON.parse(data);
    } catch (err) {
      console.log(err);
    }
  });
```

**Comment by kaelig** [comment]
The Salesforce UX team built a set of Gulp transformations to create palettes in different formats: https://github.com/salesforce-ux/theo

**Comment by kaelig** [comment]
Sassport by the talented @davidkpiano (who also made [Sassdash](https://github.com/davidkpiano/sassdash)) could be the answer to this issue.

See https://github.com/davidkpiano/sassport/

The example given is:
```js
// path/to/my-colors.js
module.exports = {
  primary: '#C0FF33'
  secondary: '#B4D455'
};
```

```css
// path/to/stylesheet.scss
$colors: require('path/to/my-colors'); // Just like Node require()!

.foo {
  color: map-get($colors, primary);
}
```

**Comment by HugoGiraudel** [comment]
Would be clean, indeed.

**Comment by onishiweb** [comment]
Do we think this is still worth looking into doing?

**Comment by kaelig** [comment]
You may want to consider using Theo: https://github.com/salesforce-ux/theo

You give it JSON, and spits out Sass + many other formats (e.g. for iOS and Android). Maybe you could make it work for colors and color use cases "à la FT" (Theo has the same basic principles behind it).

**Comment by onishiweb** [comment]
Thanks @kaelig, will have a look into that.

**Comment by AlbertoElias** [comment]
@pornel would this still be useful for the web app? We haven't heard anyone else ask for it

**Comment by pornel** [comment]
This was for the imageservice, so you could say `&bgcolor=pink`

**Comment by AlbertoElias** [comment]
Yup, I'm asking as you're the only team that asked for this feature. It's one of those that seems to make sense, but I'm not sure if in the usage we've seen of the module, that it's necessary. Most image service requests that use tinting are done via Sass, so they're constructed using o-colors.

As I said, it's one of those features that makes a lot of sense, so we shouldn't close the issue, but I've added the low priority label while nobody has a specific use case

**Comment by onishiweb** [comment]
@rowanmanning do you think this would still be useful and would there be a good way of doing this in the new image service?

**Comment by alicebartlett** [comment]
Going to close this. As @AlbertoElias says, most of the image service tint requests come via Sass which is already using o-colors to resolve to hex values.

Adding this would add a dependency on o-colors from the image service, which would need to be versioned. As we've seen with o-icons, this type of dependency can be quite a pain to manage so I'd rather not introduce it for a feature people are so apathetic about.
