### ISSUE TITLE
ft corporate blue

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-colors#91]
I'm currently working on a new b2b sign up and have discovered a blue #01509D being used that is not included in o-colors. Is it a canditate to be added to the module or has it already been depricated?

**Comment by AlbertoElias** [comment]
cc @danskinner

**Comment by danskinner** [comment]
Hi @Thurst-ft - do you have a mockup I could see? Have no record of that colour so assume it was used in error...

**Comment by onishiweb** [comment]
Any update on this or can it be closed?

**Comment by Thurst-ft** [comment]
I think this can be closed. It did not get used on the  new b2b forms so I
suspect there is no longer a user case for it.

*--*

*Thurston Tye*
Front End Developer
Technology

+44 (0)20 77756796
Number One Southwark Bridge, London SE1 9HL

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>



On 17 March 2016 at 16:46, Adam Onishi <notifications@github.com> wrote:

> Any update on this or can it be closed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-colors/issues/91#issuecomment-197969564>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by onishiweb** [comment]
Ok thanks Thurston
